---
Group:
  tableName: groups
  actAs:
    Timestampable:
      created:
        name: created_at
        type: timestamp
      updated:
        name: updated_at
        type: timestamp
  columns:
    name: string(200)
    description: string
    logo: string(200)
    url: string(150)
    area_coords: string
    user_responsible: integer
    state: integer(1)
    last_check: timestamp
    alert_count: integer(1)
    scope: string(15)
  relations:
    Admins:
      type: many
      class: Admin
      local: id
      foreign: group_id
    Responsible:
      type: one
      local: user_responsible
      foreign: id
      class: User
    Venues:
      class: Venue
      type: many
      local: id
      foreign: group_id
    ActivitySources:
      class: ActivitySource
      type: many
      local: id
      foreign: group_id

Admin:
  tableName: admins
  columns:
    user_id: integer
    group_id: integer
    role: string(100)
  relations:
    Group:
      type: one
      local: group_id
      foreign: id
    User:
      local: user_id
      foreign: id

Venue:
  tableName: venues
  columns:
    group_id: integer
    name: string(200)
    address: string
    coords: string(50)
    description: string
    icon: string(80)
  relations:
    Group:
      local: group_id
      foreign: id

ActivitySource:
  tableName: activity_sources
  columns:
    group_id: integer
    atype: string(5)
    target: string(100)
  relations:
    Group:
      local: group_id
      foreign: id
    ActivityType:
      local: atype
      foreign: atype

ActivityType:
  tableName: activity_types  
  columns:
    atype:
      type: string(5)
      primary: true
    name: string(60)
    weight: integer(2)

User:
  tableName: users
  columns:
    id:
      type: integer
      primary: true
    login: string(35)
    nick: string(60)
    name: string(80)
    email: string(150)
    url: string(200)
    bio: string
    level: string(3)
  relations:
    Group:
      local: id
      foreign: user_responsible
