<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Group extends BaseGroup
{
	public function setUp(){

		parent::setUp();
	
		$this->hasMutator('logoSrc', 'getLogoSrc');
	}
	
	
	public function getLogoSrc(){
		return $this->logo;
	}
	
}